services:
  publish-policy-default:
    build:
      context: ..
      dockerfile: Dockerfile
    environment:
      MUXCORE_GRPC_ADDR: core:9090
      MUXCORE_GRPC_INSECURE: "true"
      MUXCORE_GRPC_SEED_NODES: core-2:9090
